# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import proto.task_list_pb2 as task__list__pb2


class TaskListServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateTask = channel.unary_unary(
            '/service.proto.TaskListService/CreateTask',
            request_serializer=task__list__pb2.CreateTaskRequest.SerializeToString,
            response_deserializer=task__list__pb2.Task.FromString,
        )
        self.UpdateTask = channel.unary_unary(
            '/service.proto.TaskListService/UpdateTask',
            request_serializer=task__list__pb2.UpdateTaskRequest.SerializeToString,
            response_deserializer=task__list__pb2.Task.FromString,
        )
        self.ListTasks = channel.unary_unary(
            '/service.proto.TaskListService/ListTasks',
            request_serializer=task__list__pb2.ListTasksRequest.SerializeToString,
            response_deserializer=task__list__pb2.TaskListResponse.FromString,
        )
        self.DeleteTask = channel.unary_unary(
            '/service.proto.TaskListService/DeleteTask',
            request_serializer=task__list__pb2.DeleteTaskRequest.SerializeToString,
            response_deserializer=task__list__pb2.Task.FromString,
        )


class TaskListServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateTask(self, request, context):
        """Создать новую задачу
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateTask(self, request, context):
        """Редактировать существующую задачу
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListTasks(self, request, context):
        """Просмотреть список задач
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteTask(self, request, context):
        """Удалить задачу
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TaskListServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'CreateTask': grpc.unary_unary_rpc_method_handler(
            servicer.CreateTask,
            request_deserializer=task__list__pb2.CreateTaskRequest.FromString,
            response_serializer=task__list__pb2.Task.SerializeToString,
        ),
        'UpdateTask': grpc.unary_unary_rpc_method_handler(
            servicer.UpdateTask,
            request_deserializer=task__list__pb2.UpdateTaskRequest.FromString,
            response_serializer=task__list__pb2.Task.SerializeToString,
        ),
        'ListTasks': grpc.unary_unary_rpc_method_handler(
            servicer.ListTasks,
            request_deserializer=task__list__pb2.ListTasksRequest.FromString,
            response_serializer=task__list__pb2.TaskListResponse.SerializeToString,
        ),
        'DeleteTask': grpc.unary_unary_rpc_method_handler(
            servicer.DeleteTask,
            request_deserializer=task__list__pb2.DeleteTaskRequest.FromString,
            response_serializer=task__list__pb2.Task.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'service.proto.TaskListService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class TaskListService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateTask(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.proto.TaskListService/CreateTask',
                                             task__list__pb2.CreateTaskRequest.SerializeToString,
                                             task__list__pb2.Task.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UpdateTask(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.proto.TaskListService/UpdateTask',
                                             task__list__pb2.UpdateTaskRequest.SerializeToString,
                                             task__list__pb2.Task.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ListTasks(request,
                  target,
                  options=(),
                  channel_credentials=None,
                  call_credentials=None,
                  insecure=False,
                  compression=None,
                  wait_for_ready=None,
                  timeout=None,
                  metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.proto.TaskListService/ListTasks',
                                             task__list__pb2.ListTasksRequest.SerializeToString,
                                             task__list__pb2.TaskListResponse.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DeleteTask(request,
                   target,
                   options=(),
                   channel_credentials=None,
                   call_credentials=None,
                   insecure=False,
                   compression=None,
                   wait_for_ready=None,
                   timeout=None,
                   metadata=None):
        return grpc.experimental.unary_unary(request, target, '/service.proto.TaskListService/DeleteTask',
                                             task__list__pb2.DeleteTaskRequest.SerializeToString,
                                             task__list__pb2.Task.FromString,
                                             options, channel_credentials,
                                             insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
