# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: task_list.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ftask_list.proto\x12\rservice.proto\"7\n\x11\x43reateTaskRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"H\n\x11UpdateTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x12\n\x10ListTasksRequest\"6\n\x04Task\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"6\n\x10TaskListResponse\x12\"\n\x05tasks\x18\x01 \x03(\x0b\x32\x13.service.proto.Task\"$\n\x11\x44\x65leteTaskRequest\x12\x0f\n\x07task_id\x18\x01 \x01(\x05\x32\xaf\x02\n\x0fTaskListService\x12\x43\n\nCreateTask\x12 .service.proto.CreateTaskRequest\x1a\x13.service.proto.Task\x12\x43\n\nUpdateTask\x12 .service.proto.UpdateTaskRequest\x1a\x13.service.proto.Task\x12M\n\tListTasks\x12\x1f.service.proto.ListTasksRequest\x1a\x1f.service.proto.TaskListResponse\x12\x43\n\nDeleteTask\x12 .service.proto.DeleteTaskRequest\x1a\x13.service.proto.Taskb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'task_list_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_CREATETASKREQUEST']._serialized_start=34
  _globals['_CREATETASKREQUEST']._serialized_end=89
  _globals['_UPDATETASKREQUEST']._serialized_start=91
  _globals['_UPDATETASKREQUEST']._serialized_end=163
  _globals['_LISTTASKSREQUEST']._serialized_start=165
  _globals['_LISTTASKSREQUEST']._serialized_end=183
  _globals['_TASK']._serialized_start=185
  _globals['_TASK']._serialized_end=239
  _globals['_TASKLISTRESPONSE']._serialized_start=241
  _globals['_TASKLISTRESPONSE']._serialized_end=295
  _globals['_DELETETASKREQUEST']._serialized_start=297
  _globals['_DELETETASKREQUEST']._serialized_end=333
  _globals['_TASKLISTSERVICE']._serialized_start=336
  _globals['_TASKLISTSERVICE']._serialized_end=639
# @@protoc_insertion_point(module_scope)
